/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package belajarnetbeans;

/**
 *
 * @author aryaa
 */
public class KalkulatorNew extends javax.swing.JFrame {

    /**
     * Creates new form KalkulatorNew
     */
    public KalkulatorNew() {
        initComponents();
    }
    
    public static String removeLastChars(String str, int chars) {
        // str.substring adalah fungsi untuk merubah string
        // str.length adalah fungsi untuk menghitung jumlah character pada string
        return str.substring(0, str.length() - chars);
    }
    
    public static String removeLastChar(String str) {
        // menghapus satu karakter terakhir dari string
        return str.substring(0, str.length() - 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAngka1 = new javax.swing.JTextField();
        txtAngka2 = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnBagi = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnKurang = new javax.swing.JButton();
        btnKali = new javax.swing.JButton();
        btnEquals = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAngka1.setEditable(false);
        txtAngka1.setBackground(new java.awt.Color(255, 255, 255));
        txtAngka1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtAngka1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAngka1.setText("0");

        txtAngka2.setEditable(false);
        txtAngka2.setBackground(new java.awt.Color(255, 255, 255));
        txtAngka2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtAngka2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAngka2.setText("0");

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnBagi.setText("/");
        btnBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBagiActionPerformed(evt);
            }
        });

        btnTambah.setText("+");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnKurang.setText("-");
        btnKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKurangActionPerformed(evt);
            }
        });

        btnKali.setText("X");
        btnKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaliActionPerformed(evt);
            }
        });

        btnEquals.setText("=");
        btnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualsActionPerformed(evt);
            }
        });

        btnDelete.setText("DEL");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(btnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKali, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtAngka2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtAngka1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtAngka1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAngka2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKali, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBagiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBagiActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // mengambil string dari txtAngka1
        String angka1 = txtAngka1.getText();
        // deklarasi operator +
        String operator = "+";
        
        // Jika karakter terakhir dari txtAngka1 adalah tanda +
        if(angka1.endsWith(operator)){
            // Tidak bisa menambah lagi tanda +
            String totalAngka1 = angka1;
        }else{
            // Menambah tanda + di akhir string
            String totalAngka1 = angka1 + operator;
            txtAngka1.setText(totalAngka1);
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKurangActionPerformed

    private void btnKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKaliActionPerformed

    private void btnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEqualsActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // deklarasi variabel txtAngka1 dan txtAngka2
        String jumlahAngka = txtAngka1.getText();
        String jumlahAngka2 = txtAngka2.getText();
        // mengambil jumlah karakter dari variabel jumlahAngka
        int totalChar = jumlahAngka.length();
        // membuat variabel untuk menghapus karakter terakhir
        String delete1 = removeLastChar(jumlahAngka);
        String delete2 = removeLastChar(jumlahAngka2);
        
        // jika jumlah angka nya = 0
        if(jumlahAngka.equals("0")){
            // Angka 0 diubah menjadi angka 1
            String totalAngka = "0";
            txtAngka1.setText(totalAngka);
        }else if(jumlahAngka.isEmpty()){
            // Angka 0 diubah menjadi angka 1
            String totalAngka = "0";
            txtAngka1.setText(totalAngka);
        }
        // jika txtAngka1 nilai nya = 1
        else if(totalChar == 1){
            String totalAngka = "0";
            txtAngka1.setText(totalAngka);
        }
        // jika txt angka 2 ada isi nya
        else if(txtAngka2.getText().length() >= 1)
        {
            // maka yang dihapus adalah charakter dari txtAngka2
            txtAngka2.setText(delete2);
        }
        // Jika txtAngka1 ada isi nya dan belum meng-klik operator
        else{
          // Maka yang dihapus adalah karakter txtAngka1
          txtAngka1.setText(delete1);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtAngka1.setText("0");
        txtAngka2.setText("0");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // Get angka dari text field
        String jumlahAngka = txtAngka1.getText();
        
        // Jika angka nya = 0
        if(jumlahAngka.equals("0")){
            // Angka 0 diubah menjadi angka 1
            String totalAngka = "1";
            txtAngka1.setText(totalAngka);
        }
        else if(jumlahAngka.isEmpty()){
            // Angka menjadi 1
            String totalAngka = "1";
            txtAngka1.setText(totalAngka);
        }
        // Jika text1 diakhiri dengan tanda +
        else if(jumlahAngka.endsWith("+")){
            // ambil nilai txtAngka2
            String angka2 = txtAngka2.getText();
            String totalAngka = "1";
            
            // jika angka2 adalah 0
            if(angka2.equals("0")){
                // Angka 0 diubah menjadi angka 1
                txtAngka2.setText(totalAngka);
            }else{
                // jika angka 0 sudah diubah menjadi 1, maka menambahkan angka 1 terus menerus
                txtAngka2.setText(angka2 + totalAngka);
            }
        }
        // Jika angka bukan 0
        else{
          // Menambahkan jumlah angka 1 di belakang angka terakhir
          String totalAngka = jumlahAngka + "1";
          txtAngka1.setText(totalAngka);
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // Get angka dari text field
        String jumlahAngka = txtAngka1.getText();
        
        // Jika angka nya = 0
        if(jumlahAngka.equals("0")){
            // Angka 0 diubah menjadi angka 2
            String totalAngka = "2";
            txtAngka1.setText(totalAngka);
        }else if(jumlahAngka.isEmpty()){
            // Angka 0 diubah menjadi angka 2
            String totalAngka = "2";
            txtAngka1.setText(totalAngka);
        }
        // Jika angka bukan 0
        else{
          // Menambahkan jumlah angka 1 di belakang angka terakhir
          String totalAngka = jumlahAngka + "2";
          txtAngka1.setText(totalAngka);
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // Get angka dari text field
        String jumlahAngka = txtAngka1.getText();
        
        // Jika angka nya = 0
        if(jumlahAngka.equals("0")){
            // Angka 0 diubah menjadi angka 
            String totalAngka = "3";
            txtAngka1.setText(totalAngka);
        }else if(jumlahAngka.isEmpty()){
            // Angka 0 diubah menjadi angka 3
            String totalAngka = "3";
            txtAngka1.setText(totalAngka);
        }
        // Jika angka bukan 0
        else{
          // Menambahkan jumlah angka 3 di belakang angka terakhir
          String totalAngka = jumlahAngka + "3";
          txtAngka1.setText(totalAngka);
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // Get angka dari text field
        String jumlahAngka = txtAngka1.getText();
        
        // Jika angka nya = 0
        if(jumlahAngka.equals("0")){
            // Angka 0 diubah menjadi angka 
            String totalAngka = "4";
            txtAngka1.setText(totalAngka);
        }else if(jumlahAngka.isEmpty()){
            // Angka 0 diubah menjadi angka 4
            String totalAngka = "4";
            txtAngka1.setText(totalAngka);
        }
        // Jika angka bukan 0
        else{
          // Menambahkan jumlah angka 4 di belakang angka terakhir
          String totalAngka = jumlahAngka + "4";
          txtAngka1.setText(totalAngka);
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // Get angka dari text field
        String jumlahAngka = txtAngka1.getText();
        
        // Jika angka nya = 0
        if(jumlahAngka.equals("0")){
            // Angka 0 diubah menjadi angka 
            String totalAngka = "5";
            txtAngka1.setText(totalAngka);
        }else if(jumlahAngka.isEmpty()){
            // Angka 0 diubah menjadi angka 5
            String totalAngka = "5";
            txtAngka1.setText(totalAngka);
        }
        // Jika angka bukan 0
        else{
          // Menambahkan jumlah angka 5 di belakang angka terakhir
          String totalAngka = jumlahAngka + "5";
          txtAngka1.setText(totalAngka);
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // Get angka dari text field
        String jumlahAngka = txtAngka1.getText();
        
        // Jika angka nya = 0
        if(jumlahAngka.equals("0")){
            // Angka 0 diubah menjadi angka 
            String totalAngka = "6";
            txtAngka1.setText(totalAngka);
        }else if(jumlahAngka.isEmpty()){
            // Angka 0 diubah menjadi angka 6
            String totalAngka = "6";
            txtAngka1.setText(totalAngka);
        }
        // Jika angka bukan 0
        else{
          // Menambahkan jumlah angka 6 di belakang angka terakhir
          String totalAngka = jumlahAngka + "6";
          txtAngka1.setText(totalAngka);
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // Get angka dari text field
        String jumlahAngka = txtAngka1.getText();
        
        // Jika angka nya = 0
        if(jumlahAngka.equals("0")){
            // Angka 0 diubah menjadi angka 
            String totalAngka = "7";
            txtAngka1.setText(totalAngka);
        }else if(jumlahAngka.isEmpty()){
            // Angka 0 diubah menjadi angka 7
            String totalAngka = "7";
            txtAngka1.setText(totalAngka);
        }
        // Jika angka bukan 0
        else{
          // Menambahkan jumlah angka 7 di belakang angka terakhir
          String totalAngka = jumlahAngka + "7";
          txtAngka1.setText(totalAngka);
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // Get angka dari text field
        String jumlahAngka = txtAngka1.getText();
        
        // Jika angka nya = 0
        if(jumlahAngka.equals("0")){
            // Angka 0 diubah menjadi angka 
            String totalAngka = "8";
            txtAngka1.setText(totalAngka);
        }else if(jumlahAngka.isEmpty()){
            // Angka 0 diubah menjadi angka 8
            String totalAngka = "8";
            txtAngka1.setText(totalAngka);
        }
        // Jika angka bukan 0
        else{
          // Menambahkan jumlah angka 8 di belakang angka terakhir
          String totalAngka = jumlahAngka + "8";
          txtAngka1.setText(totalAngka);
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // Get angka dari text field
        String jumlahAngka = txtAngka1.getText();
        
        // Jika angka nya = 0
        if(jumlahAngka.equals("0")){
            // Angka 0 diubah menjadi angka 
            String totalAngka = "9";
            txtAngka1.setText(totalAngka);
        }else if(jumlahAngka.isEmpty()){
            // Angka 0 diubah menjadi angka 9
            String totalAngka = "9";
            txtAngka1.setText(totalAngka);
        }
        // Jika angka bukan 0
        else{
          // Menambahkan jumlah angka 9 di belakang angka terakhir
          String totalAngka = jumlahAngka + "9";
          txtAngka1.setText(totalAngka);
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // Get angka dari text field
        String jumlahAngka = txtAngka1.getText();
        
        // Jika angka nya = 0
        if(jumlahAngka.equals("0")){
            // Angka 0 diubah menjadi angka 
            String totalAngka = "0";
            txtAngka1.setText(totalAngka);
        }else if(jumlahAngka.isEmpty()){
            // Angka 0 diubah menjadi angka 0
            String totalAngka = "0";
            txtAngka1.setText(totalAngka);
        }
        // Jika angka bukan 0
        else{
          // Menambahkan jumlah angka 0 di belakang angka terakhir
          String totalAngka = jumlahAngka + "0";
          txtAngka1.setText(totalAngka);
        }
    }//GEN-LAST:event_btn0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBagi;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEquals;
    private javax.swing.JButton btnKali;
    private javax.swing.JButton btnKurang;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JTextField txtAngka1;
    private javax.swing.JTextField txtAngka2;
    // End of variables declaration//GEN-END:variables
}
